### ISSUE TITLE
prior waits an extra couple of seconds before exiting 

### ISSUE THREAD

**Issue by sourencho** [SourenP/rippled-network-crawler#40]
For some reason if you call `node index.js prior <dbUrl> -s` after it returns the data it waits a couple of seconds before exiting (during which it's probably doing nothing). 

Since `forever` uses `prior`, getting rid of the waiting will get us more cpm (crawls per minute)

**Comment by intelliot** [comment]
As with the other issues in this repo, I'm closing this because it's over 5 years old and this repo has moved. But if anyone cares about this issue, please feel free to open a new one at https://github.com/xpring-eng/rippled-network-crawler/issues and write up the specifics on the work that you think should be done
