### ISSUE TITLE
src/lib/utility.normalizePubKey can be optimized

### ISSUE THREAD

**Issue by sourencho** [SourenP/rippled-network-crawler#44]
sublimator suggested 

```
function memoize(func) {
  var cache = {};

  return function memoized() {
    var key = arguments.length === 1 &&
              typeof arguments[0] === 'string' ?
                arguments[0] : JSON.stringify(arguments);
    var cached = cache[key];
    return  cached !== undefined? cached :
            cache[key] = func.apply(this, arguments);
  };
}

exports.normalizePubKey = memoize(normalizePubKey)
```

**Comment by intelliot** [comment]
As with the other issues in this repo, I'm closing this because it's over 5 years old and this repo has moved. But if anyone cares about this issue, please feel free to open a new one at https://github.com/xpring-eng/rippled-network-crawler/issues and write up the specifics on the work that you think should be done
